

--Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount 
from customer 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)


-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, 
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;

--Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;
 
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;

--Q11. Which category generates the highest total revenue?
SELECT category, 
       ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY category
ORDER BY total_revenue DESC;

--Q12. Which locations contribute the most revenue?
SELECT location, 
       ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY location
ORDER BY total_revenue DESC
LIMIT 10;

--Q13. What is the average spending behavior per season?
SELECT season,
       ROUND(AVG(purchase_amount), 2) AS avg_spend,
       ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY season
ORDER BY total_revenue DESC;

--Q14. Do customers who leave higher reviews spend more?
SELECT 
    CASE 
        WHEN review_rating >= 4 THEN 'High Rating (4-5)'
        WHEN review_rating >= 3 THEN 'Medium Rating (3)'
        ELSE 'Low Rating (1-2)'
    END AS rating_segment,
    ROUND(AVG(purchase_amount), 2) AS avg_spend
FROM customer
GROUP BY rating_segment;

--Q15. What is the revenue split between discount vs non-discount purchases?
SELECT discount_applied,
       COUNT(*) AS total_orders,
       ROUND(SUM(purchase_amount), 2) AS total_revenue,
       ROUND(AVG(purchase_amount), 2) AS avg_order_value
FROM customer
GROUP BY discount_applied;

--Q16. Which payment method is most popular and generates most revenue?
SELECT payment_method,
       COUNT(*) AS total_orders,
       ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY payment_method
ORDER BY total_revenue DESC;

--17Q. Which age group is most price-sensitive (uses discounts most)?
SELECT age_group,
       COUNT(*) AS total_orders,
       SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) AS discount_orders,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_usage_percent
FROM customer
GROUP BY age_group
ORDER BY discount_usage_percent DESC;

--18Q. Which customers are high-value customers?
SELECT customer_id,
       SUM(purchase_amount) AS lifetime_value
FROM customer
GROUP BY customer_id
HAVING SUM(purchase_amount) > (SELECT AVG(purchase_amount) FROM customer)
ORDER BY lifetime_value DESC;

--19Q. How does purchase frequency affect revenue?
SELECT frequency_of_purchases,
       COUNT(*) AS customers,
       ROUND(AVG(purchase_amount), 2) AS avg_spend,
       ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY frequency_of_purchases
ORDER BY total_revenue DESC;

--20Q. Which category has the most loyal customers?
SELECT category,
       COUNT(CASE WHEN previous_purchases > 10 THEN 1 END) AS loyal_customers
FROM customer
GROUP BY category
ORDER BY loyal_customers DESC;
